//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plex2Sonos.Plex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlexHeaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlexHeaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plex2Sonos.Plex.PlexHeaders", typeof(PlexHeaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Client-Identifier.
        /// </summary>
        public static string X_PLEX_CLIENT_IDENTIFIER {
            get {
                return ResourceManager.GetString("X_PLEX_CLIENT_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Container-Size.
        /// </summary>
        public static string X_PLEX_CONTAINER_SIZE {
            get {
                return ResourceManager.GetString("X_PLEX_CONTAINER_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Container-Start.
        /// </summary>
        public static string X_PLEX_CONTAINER_START {
            get {
                return ResourceManager.GetString("X_PLEX_CONTAINER_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Device.
        /// </summary>
        public static string X_PLEX_DEVICE {
            get {
                return ResourceManager.GetString("X_PLEX_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Platform.
        /// </summary>
        public static string X_PLEX_PLATFORM {
            get {
                return ResourceManager.GetString("X_PLEX_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Platform-Version.
        /// </summary>
        public static string X_PLEX_PLATFORM_VERSION {
            get {
                return ResourceManager.GetString("X_PLEX_PLATFORM_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Product.
        /// </summary>
        public static string X_PLEX_PRODUCT {
            get {
                return ResourceManager.GetString("X_PLEX_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Provides.
        /// </summary>
        public static string X_PLEX_PROVIDES {
            get {
                return ResourceManager.GetString("X_PLEX_PROVIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plex-Version.
        /// </summary>
        public static string X_PLEX_VERSION {
            get {
                return ResourceManager.GetString("X_PLEX_VERSION", resourceCulture);
            }
        }
    }
}
